### ISSUE TITLE
Custom element doesn't exist: network-tariff-card.

### ISSUE THREAD

**Issue by bovcan** [frlequ/network-tariff-card#10]
Odkar sem update-al mi ne prikaže več "urce".
Custom element doesn't exist: network-tariff-card.
če spremenim type: entity mi kaže samo ikonco in številko.

**Comment by frlequ** [comment]
Treba bo narediti clear cache.

**Comment by frlequ** [comment]
Ups... pod Releases je bila pripeta napačna datoteka. Sem posodobil in bi sedaj nova verzija morala delovati.

![image](https://github.com/user-attachments/assets/14f9edfe-f150-40a2-946f-496a4326b4a9)

**Comment by bovcan** [comment]
sedaj, pa špila.
