### ISSUE TITLE
The card does not show if there is no internet connection

### ISSUE THREAD

**Issue by trozman** [frlequ/network-tariff-card#13]
When internet is down, the card shows the following:
![image](https://github.com/user-attachments/assets/62502d00-da21-47f9-8a34-e6ede64da915)

As soon the internet is back, the card shows normally.
The same happens on my FireHD tab, which often puts wifi to sleep. Before it wakes up the connection(it takes few seconds), the card is shown as above. All other cards (that do not depend on internet) are shown ok.

**Comment by frlequ** [comment]
Created new release [1.0.5](https://github.com/frlequ/network-tariff-card/releases) with PR https://github.com/frlequ/network-tariff-card/pull/14

This should be fixed now. The `LitElement` library has been bundled with the card, so it no longer relies on an external import (internet). Please update and thank you for reporting this issue!

**Comment by trozman** [comment]
Thanks for the update!
