### ISSUE TITLE
Tariff card not loading

### ISSUE THREAD

**Issue by erikklavora** [frlequ/network-tariff-card#3]
Ok, so I have a problem installing the network-tariff-card, well not installing as it should be installed, but rather displaying it on the Dashboard. the elektro-network-tariff is installed and I can see all the params under Dev tools -> states for sensor.elektro_network_tariff. I'm running HA v2024.9.2 and the error I get on the dashboard is: "i.setConfig is not a function;"

**Comment by frlequ** [comment]
Thx, can you also include your yaml for card?

**Comment by frlequ** [comment]
Please update, and report back if still an issue:
https://github.com/frlequ/network-tariff-card/releases/tag/1.0.1

**Comment by erikklavora** [comment]
Hi, sorry for late reply… was on vacations… I updated it and it’s working now.

**Comment by frlequ** [comment]
Thx for feedback!
