### ISSUE TITLE
Rotation of numbers

### ISSUE THREAD

**Issue by MatejKovacic** [frlequ/network-tariff-card#4]
I think that current chart visualisation could be improved, because it is not enough intuitive (at least for me). I believe it would be better if numbers would be rotated, so they would more resemble to clock.

Here is what I have in mind:

![image](https://github.com/user-attachments/assets/7ac2470c-a408-40b9-8a74-3c8b1810ef6d)

In that case you can easily see that current block is between 11 and 12.

What do you think?

**Comment by frlequ** [comment]
Added in the latest release:
https://github.com/frlequ/network-tariff-card/releases/tag/1.0.1
