### ISSUE TITLE
color coding not working

### ISSUE THREAD

**Issue by tislar** [frlequ/network-tariff-card#6]
![image](https://github.com/user-attachments/assets/f3e736c8-cd7a-4eaa-97d9-48c5482d4ad6)

**Comment by frlequ** [comment]
Which version of Elektro Network Tariff integration are you using?

In the latest version, under the developers tools you should see `blocks` attribute:
![image](https://github.com/user-attachments/assets/21f1b6fc-afe3-4034-a060-f026633ce4cb)

**Comment by tislar** [comment]
I m using last one, but it seems there are no blocks?
![Screenshot_20241014_223030_Home Assistant](https://github.com/user-attachments/assets/659c5c0d-d27e-4ab9-8592-d9a50ad48eab)
![Screenshot_20241014_223140_Home Assistant](https://github.com/user-attachments/assets/9c61cc04-5f19-4740-a7c0-37dd9866b193)

**Comment by frlequ** [comment]
It looks like you are still using old version. Please update elektro_network_tariff **component** (NOT THE CARD).

https://github.com/frlequ/home-assistant-network-tariff

Also restart HA after upgrade.

**Comment by tislar** [comment]
Thanks. That saved the problem. Sorry for any troubles, didn't know there was second thing to install.

**Comment by tislar** [comment]
Thanks. That saved the problem. Sorry for any troubles, didn't know there was second thing to install.
