### ISSUE TITLE
Pointer not refreshing according to current time

### ISSUE THREAD

**Issue by blazx6** [frlequ/network-tariff-card#9]
The Dial represents the hours of the day and the Pointer points to the current Time block. I had the HA Dashboard open and the Network Tariff Number, located in the center, was updating accordingly. The Time block pointer was not moving and was not in sync with the current Time. I had to refresh/reopen the Dashboard for the Pointer to synchronize and point towards the actual Time block.

Example from yesterday evening:

- We were in the 2. Network Tariff and the Network Tariff Number and Time Block Pointer were in sync and showing accurate Values.
-  We moved from the 2. Network Tariff to the 3. Network Tariff. Network Tariff Number was updated immediately, Time Block Pointer was still pointing to the previous Time Block and wasn't updating.

I hope I explained the issue and you will be able to recreate it.

**Comment by frlequ** [comment]
The fix was merged yesterday  https://github.com/frlequ/network-tariff-card/pull/8. Please update the card.

Please report any issue.

**Comment by blazx6** [comment]
I will do it right away and observe the behaviour. I was just setting up the card yesterday evening and I see now that a new version of the component is available. Thanks for the effort!
